// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: it8wKNwdwafZt73hiEPwUt
// Component: m-mvLf1xdKuM
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: it8wKNwdwafZt73hiEPwUt/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: m-mvLf1xdKuM/css
import Topology1Icon from "./icons/PlasmicIcon__Topology1"; // plasmic-import: 1JnmYMEAw/icon
import Union2Icon from "./icons/PlasmicIcon__Union2"; // plasmic-import: wWnnFnd6K4/icon
import Union5Icon from "./icons/PlasmicIcon__Union5"; // plasmic-import: w_ySx-x0LY/icon
import Line82Icon from "./icons/PlasmicIcon__Line82"; // plasmic-import: 8996ZNBw63/icon
import Ellipse287Icon from "./icons/PlasmicIcon__Ellipse287"; // plasmic-import: ApTLFc7gee/icon
import Line75Icon from "./icons/PlasmicIcon__Line75"; // plasmic-import: jmpH7tc7zE/icon
import Line81Icon from "./icons/PlasmicIcon__Line81"; // plasmic-import: KA25P20g0nj/icon
import Line85Icon from "./icons/PlasmicIcon__Line85"; // plasmic-import: sVm1ItQcXTc/icon
import Line87Icon from "./icons/PlasmicIcon__Line87"; // plasmic-import: 8AoRpPPHmZM/icon
import Line76Icon from "./icons/PlasmicIcon__Line76"; // plasmic-import: fYd8WGLsGAz/icon
import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: d09mZP7-mcI/icon
import Line73Icon from "./icons/PlasmicIcon__Line73"; // plasmic-import: Ah8Kqz2GZoh/icon
import Line78Icon from "./icons/PlasmicIcon__Line78"; // plasmic-import: xv5sKZ4mc6f/icon
import Union8Icon from "./icons/PlasmicIcon__Union8"; // plasmic-import: Bzqcv8-KwH-/icon
import Union9Icon from "./icons/PlasmicIcon__Union9"; // plasmic-import: 9UCn58LuGPT/icon
import Union11Icon from "./icons/PlasmicIcon__Union11"; // plasmic-import: QYnnlufmzWe/icon
import Union12Icon from "./icons/PlasmicIcon__Union12"; // plasmic-import: JfUOuZeVm7m/icon
import Rectangle22704Icon from "./icons/PlasmicIcon__Rectangle22704"; // plasmic-import: ov_CJHB2xP_/icon
import Ellipse288Icon from "./icons/PlasmicIcon__Ellipse288"; // plasmic-import: 88tPlVi7QMZ/icon
import Line80Icon from "./icons/PlasmicIcon__Line80"; // plasmic-import: oXOL5hlVVSt/icon
import Ellipse303Icon from "./icons/PlasmicIcon__Ellipse303"; // plasmic-import: etfstOJ8gFx/icon
import Union14Icon from "./icons/PlasmicIcon__Union14"; // plasmic-import: Jpb2hnNjELx/icon
import Union15Icon from "./icons/PlasmicIcon__Union15"; // plasmic-import: JarXmWTlN3U/icon
import group3055HXkanzHMh5 from "./images/group3055.bin"; // plasmic-import: HXkanzHMh5/picture
import topology12O6Ga6Dym1H from "./images/topology12.bin"; // plasmic-import: o6Ga6DYM1h/picture
import topology13D6GR6QAw3B from "./images/topology13.bin"; // plasmic-import: D6gR6qAw3B/picture
import unionH4UOy82K5M from "./images/union.bin"; // plasmic-import: h4UOy82K5m/picture
import union39Cl4Lf8V81 from "./images/union3.bin"; // plasmic-import: 9CL4LF8v81/picture
import union4KlRqaEm5YN from "./images/union4.bin"; // plasmic-import: KLRqaEm5yN/picture
import union6QzQbcBhuaV from "./images/union6.bin"; // plasmic-import: QzQBCBhuaV/picture
import rectangle226659N80NnT7Uj from "./images/rectangle22665.bin"; // plasmic-import: 9N80nnT7Uj/picture
import iconArrowDownCircleJPrbMiFvGd from "./images/iconArrowDownCircle.bin"; // plasmic-import: JPrbMIFvGD/picture
import iconArrowDownCircle2YobaFuDm26 from "./images/iconArrowDownCircle2.bin"; // plasmic-import: YobaFuDm26/picture
import rectangle22664Fb5BWkVaqCd from "./images/rectangle22664.bin"; // plasmic-import: Fb5BWkVAQCd/picture
import ellipse245ZoZqkrfQbTp from "./images/ellipse245.bin"; // plasmic-import: ZoZqkrfQBTp/picture
import union7LuWdpOslfOe from "./images/union7.bin"; // plasmic-import: LuWdpOSLFOe/picture
import vector2DiyEuKsIdH from "./images/vector2.bin"; // plasmic-import: diyEuKS-idH/picture
import maskGroupBli06OE0LN from "./images/maskGroup.bin"; // plasmic-import: Bli0-6oE0lN/picture
import iconArrowDownCircle3FraWzkEdthp from "./images/iconArrowDownCircle3.bin"; // plasmic-import: fraWzkEDTHP/picture
import iconArrowDownCircle466Z0Y4Xmkyl from "./images/iconArrowDownCircle4.bin"; // plasmic-import: 66z0Y4Xmkyl/picture
import union10ODg7GnkHjdU from "./images/union10.bin"; // plasmic-import: oDg7GNKHjdU/picture
import vector3Cf2Ccicofx from "./images/vector3.bin"; // plasmic-import: CF_2Ccicofx/picture
import maskGroup2IjHoEksC8Si from "./images/maskGroup2.bin"; // plasmic-import: IJHoEksC8si/picture
import iconArrowDownCircle5MtoDdHGcS6 from "./images/iconArrowDownCircle5.bin"; // plasmic-import: mtoDdHGc_s6/picture
import iconArrowDownCircle62T01FdZwcin from "./images/iconArrowDownCircle6.bin"; // plasmic-import: 2t01FDZwcin/picture
import vector4E3E4PbP5Bqn from "./images/vector4.bin"; // plasmic-import: e3E4PbP5BQN/picture
import iconShoppingCart6IZqEOiUq from "./images/iconShoppingCart.bin"; // plasmic-import: 6I-Zq-EOiUq/picture
import iconArrowDownCircle7SBlIKsq5M4 from "./images/iconArrowDownCircle7.bin"; // plasmic-import: S_BlIKsq5m4/picture
import union13ISTlF5VkA from "./images/union13.bin"; // plasmic-import: -iSTlF5vk_a/picture
import vector5SDj54U1OSi from "./images/vector5.bin"; // plasmic-import: sDJ54-U1oSi/picture
import maskGroup3Mw7VoSjZaGe from "./images/maskGroup3.bin"; // plasmic-import: Mw7voSjZAGe/picture

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"dashboard"}
            data-plasmic-override={overrides.dashboard}
            className={classNames(projectcss.all, sty.dashboard)}
          >
            <Topology1Icon
              className={classNames(projectcss.all, sty.svg___6QEzj)}
              role={"img"}
            />

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__ok5Md)}
              displayHeight={"687.906px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"670.916px"}
              loading={"lazy"}
              src={{
                src: group3055HXkanzHMh5,
                fullWidth: 670.916,
                fullHeight: 687.906,
                aspectRatio: 0.982794
              }}
            />

            {false ? (
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__oleZq)}
                displayHeight={"857.488px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"878px"}
                loading={"lazy"}
                src={{
                  src: topology12O6Ga6Dym1H,
                  fullWidth: 878,
                  fullHeight: 857.488,
                  aspectRatio: 1.02411
                }}
              />
            ) : null}
            {false ? (
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__yLeB)}
                displayHeight={"857.488px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"878px"}
                loading={"lazy"}
                src={{
                  src: topology13D6GR6QAw3B,
                  fullWidth: 878,
                  fullHeight: 857.488,
                  aspectRatio: 1.02411
                }}
              />
            ) : null}
            {false ? (
              <div
                data-plasmic-name={"group241"}
                data-plasmic-override={overrides.group241}
                className={classNames(projectcss.all, sty.group241)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__onhTi)}
                  displayHeight={"2746px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"2092px"}
                  loading={"lazy"}
                  src={{
                    src: unionH4UOy82K5M,
                    fullWidth: 2092,
                    fullHeight: 2746,
                    aspectRatio: 0.761835
                  }}
                />

                <Union2Icon
                  className={classNames(projectcss.all, sty.svg__p3EA0)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"maskGroup"}
                  data-plasmic-override={overrides.maskGroup}
                  className={classNames(projectcss.all, sty.maskGroup)}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__cl6Rm)}
                  displayHeight={"2372px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"1803px"}
                  loading={"lazy"}
                  src={{
                    src: union39Cl4Lf8V81,
                    fullWidth: 1803,
                    fullHeight: 2372,
                    aspectRatio: 0.760118
                  }}
                />
              </div>
            ) : null}
            {false ? (
              <div
                data-plasmic-name={"group375"}
                data-plasmic-override={overrides.group375}
                className={classNames(projectcss.all, sty.group375)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__nNa0S)}
                  displayHeight={"2746px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"2092px"}
                  loading={"lazy"}
                  src={{
                    src: union4KlRqaEm5YN,
                    fullWidth: 2092,
                    fullHeight: 2746,
                    aspectRatio: 0.761835
                  }}
                />

                <Union5Icon
                  className={classNames(projectcss.all, sty.svg__lii3A)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"maskGroup2"}
                  data-plasmic-override={overrides.maskGroup2}
                  className={classNames(projectcss.all, sty.maskGroup2)}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__xg3J9)}
                  displayHeight={"2372px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"1803px"}
                  loading={"lazy"}
                  src={{
                    src: union6QzQbcBhuaV,
                    fullWidth: 1803,
                    fullHeight: 2372,
                    aspectRatio: 0.760118
                  }}
                />
              </div>
            ) : null}

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__xdn7L)}
              displayHeight={"202px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"646px"}
              loading={"lazy"}
              src={{
                src: rectangle226659N80NnT7Uj,
                fullWidth: 646,
                fullHeight: 202,
                aspectRatio: 3.19802
              }}
            />

            <Line82Icon
              className={classNames(projectcss.all, sty.svg__e3DE)}
              role={"img"}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__uaY4M
              )}
            >
              {"Boardroom"}
            </div>

            <div
              data-plasmic-name={"bshares"}
              data-plasmic-override={overrides.bshares}
              className={classNames(projectcss.all, sty.bshares)}
            />

            <div
              data-plasmic-name={"group3029"}
              data-plasmic-override={overrides.group3029}
              className={classNames(projectcss.all, sty.group3029)}
            >
              <div
                data-plasmic-name={"bshares2"}
                data-plasmic-override={overrides.bshares2}
                className={classNames(projectcss.all, sty.bshares2)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mQkVy
                )}
              >
                {"Your Stake: \n    6.0000\n≈ $1171.62"}
              </div>
            </div>

            <div
              data-plasmic-name={"group3030"}
              data-plasmic-override={overrides.group3030}
              className={classNames(projectcss.all, sty.group3030)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___5MY3F
                )}
              >
                {"Earned: \n    1660.4413 \n≈ $298.88"}
              </div>

              <div
                data-plasmic-name={"bomb"}
                data-plasmic-override={overrides.bomb}
                className={classNames(projectcss.all, sty.bomb)}
              />
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ucyK8
              )}
            >
              {"Stake BSHARE and earn BOMB every epoch"}
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"withdrawButtons"}
              data-plasmic-override={overrides.withdrawButtons}
              hasGap={true}
              className={classNames(projectcss.all, sty.withdrawButtons)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__h8Kxg
                )}
              >
                {"Withdraw"}
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__qqrK)}
                displayHeight={"21px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"21px"}
                loading={"lazy"}
                src={{
                  src: iconArrowDownCircleJPrbMiFvGd,
                  fullWidth: 21,
                  fullHeight: 21,
                  aspectRatio: 1
                }}
              />
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"depositButtons"}
              data-plasmic-override={overrides.depositButtons}
              hasGap={true}
              className={classNames(projectcss.all, sty.depositButtons)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___2ByDx
                )}
              >
                {"Deposit"}
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__ffpFu)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__cVSa8)}
                  displayHeight={"21px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"21px"}
                  loading={"lazy"}
                  src={{
                    src: iconArrowDownCircle2YobaFuDm26,
                    fullWidth: 21,
                    fullHeight: 21,
                    aspectRatio: 1
                  }}
                />
              </div>
            </p.Stack>

            <div
              data-plasmic-name={"dailyReturns2"}
              data-plasmic-override={overrides.dailyReturns2}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.dailyReturns2
              )}
            >
              {"Daily Returns:\n2% \r"}
            </div>

            <div
              data-plasmic-name={"group3053"}
              data-plasmic-override={overrides.group3053}
              className={classNames(projectcss.all, sty.group3053)}
            >
              <div
                data-plasmic-name={"group3082"}
                data-plasmic-override={overrides.group3082}
                className={classNames(projectcss.all, sty.group3082)}
              >
                <div
                  data-plasmic-name={"rectangle22674"}
                  data-plasmic-override={overrides.rectangle22674}
                  className={classNames(projectcss.all, sty.rectangle22674)}
                />

                <Ellipse287Icon
                  className={classNames(projectcss.all, sty.svg__h8PJy)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"group3042"}
                  data-plasmic-override={overrides.group3042}
                  className={classNames(projectcss.all, sty.group3042)}
                >
                  <div
                    data-plasmic-name={"bbond"}
                    data-plasmic-override={overrides.bbond}
                    className={classNames(projectcss.all, sty.bbond)}
                  />
                </div>
              </div>
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__uVDrx
              )}
            >
              {"Current Epoch\n258"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___9VqAg
              )}
            >
              {"03:38:36\nNext Epoch in"}
            </div>

            <Line75Icon
              className={classNames(projectcss.all, sty.svg__afrta)}
              role={"img"}
            />

            <Line81Icon
              className={classNames(projectcss.all, sty.svg__wiHzO)}
              role={"img"}
            />

            <Line85Icon
              className={classNames(projectcss.all, sty.svg__hfl23)}
              role={"img"}
            />

            <Line85Icon
              className={classNames(projectcss.all, sty.svg__zYAjN)}
              role={"img"}
            />

            <Line87Icon
              className={classNames(projectcss.all, sty.svg__h6BA)}
              role={"img"}
            />

            <Line87Icon
              className={classNames(projectcss.all, sty.svg___75Aqk)}
              role={"img"}
            />

            <Line76Icon
              className={classNames(projectcss.all, sty.svg__a0MPg)}
              role={"img"}
            />

            <div
              data-plasmic-name={"unity"}
              data-plasmic-override={overrides.unity}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.unity
              )}
            >
              {"$BOMB"}
            </div>

            <div
              data-plasmic-name={"group3441"}
              data-plasmic-override={overrides.group3441}
              className={classNames(projectcss.all, sty.group3441)}
            >
              <Ellipse287Icon
                className={classNames(projectcss.all, sty.svg__esk0)}
                role={"img"}
              />

              <div
                data-plasmic-name={"bshares3"}
                data-plasmic-override={overrides.bshares3}
                className={classNames(projectcss.all, sty.bshares3)}
              />
            </div>

            <div
              data-plasmic-name={"unity2"}
              data-plasmic-override={overrides.unity2}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.unity2
              )}
            >
              {"$BSHARE"}
            </div>

            <div
              data-plasmic-name={"group3084"}
              data-plasmic-override={overrides.group3084}
              className={classNames(projectcss.all, sty.group3084)}
            >
              <div
                data-plasmic-name={"unity3"}
                data-plasmic-override={overrides.unity3}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.unity3
                )}
              >
                {"11.43K"}
              </div>

              <div
                data-plasmic-name={"unity4"}
                data-plasmic-override={overrides.unity4}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.unity4
                )}
              >
                {"8.49m"}
              </div>

              <div
                data-plasmic-name={"unity5"}
                data-plasmic-override={overrides.unity5}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.unity5
                )}
              >
                {"$300\n13000 BTCB"}
              </div>

              <div
                data-plasmic-name={"wMetaMask"}
                data-plasmic-override={overrides.wMetaMask}
                className={classNames(projectcss.all, sty.wMetaMask)}
              />
            </div>

            <div
              data-plasmic-name={"unity6"}
              data-plasmic-override={overrides.unity6}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.unity6
              )}
            >
              {"$BBOND"}
            </div>

            <div
              data-plasmic-name={"group3085"}
              data-plasmic-override={overrides.group3085}
              className={classNames(projectcss.all, sty.group3085)}
            >
              <div
                data-plasmic-name={"unity7"}
                data-plasmic-override={overrides.unity7}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.unity7
                )}
              >
                {"20.00K"}
              </div>

              <div
                data-plasmic-name={"unity8"}
                data-plasmic-override={overrides.unity8}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.unity8
                )}
              >
                {"175k"}
              </div>

              <div
                data-plasmic-name={"unity9"}
                data-plasmic-override={overrides.unity9}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.unity9
                )}
              >
                {"$0.28\n1.15 BTCB"}
              </div>

              <div
                data-plasmic-name={"wMetaMask2"}
                data-plasmic-override={overrides.wMetaMask2}
                className={classNames(projectcss.all, sty.wMetaMask2)}
              />
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__gcAh5
              )}
            >
              {"Last Epoch TWAP: 1.22"}
            </div>

            <div
              data-plasmic-name={"unitePriceTwap"}
              data-plasmic-override={overrides.unitePriceTwap}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.unitePriceTwap
              )}
            >
              {"Live TWAP: 1.17"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__uKnk6
              )}
            >
              {"TVL: $5,002,412"}
            </div>

            <div
              data-plasmic-name={"group3083"}
              data-plasmic-override={overrides.group3083}
              className={classNames(projectcss.all, sty.group3083)}
            >
              <div
                data-plasmic-name={"wMetaMask3"}
                data-plasmic-override={overrides.wMetaMask3}
                className={classNames(projectcss.all, sty.wMetaMask3)}
              />

              <div
                data-plasmic-name={"unity10"}
                data-plasmic-override={overrides.unity10}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.unity10
                )}
              >
                {"$0.24 \n1.05 BTCB"}
              </div>

              <div
                data-plasmic-name={"unity11"}
                data-plasmic-override={overrides.unity11}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.unity11
                )}
              >
                {"8.66M"}
              </div>

              <div
                data-plasmic-name={"unity12"}
                data-plasmic-override={overrides.unity12}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.unity12
                )}
              >
                {" 60.9k"}
              </div>
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__iyTzk
              )}
            >
              {"Bomb Finance Summary"}
            </div>

            <div
              data-plasmic-name={"rectangle22703"}
              data-plasmic-override={overrides.rectangle22703}
              className={classNames(projectcss.all, sty.rectangle22703)}
            />

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame540"}
              data-plasmic-override={overrides.frame540}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame540)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__b6388
                )}
              >
                {"Recommended"}
              </div>
            </p.Stack>

            <div
              data-plasmic-name={"group3068"}
              data-plasmic-override={overrides.group3068}
              className={classNames(projectcss.all, sty.group3068)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cCoyn
                )}
              >
                {"Total Staked:      7232"}
              </div>

              <div
                data-plasmic-name={"bshares4"}
                data-plasmic-override={overrides.bshares4}
                className={classNames(projectcss.all, sty.bshares4)}
              />
            </div>

            <div
              data-plasmic-name={"group2924"}
              data-plasmic-override={overrides.group2924}
              className={classNames(projectcss.all, sty.group2924)}
            >
              <div
                data-plasmic-name={"group2904"}
                data-plasmic-override={overrides.group2904}
                className={classNames(projectcss.all, sty.group2904)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"frame679"}
                  data-plasmic-override={overrides.frame679}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame679)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__a8F8B
                    )}
                  >
                    {"Read Investment Strategy"}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__iZCf3)}
                  >
                    <VectorIcon
                      className={classNames(projectcss.all, sty.svg__liA)}
                      role={"img"}
                    />
                  </div>
                </p.Stack>
              </div>
            </div>

            <div
              data-plasmic-name={"group3074"}
              data-plasmic-override={overrides.group3074}
              className={classNames(projectcss.all, sty.group3074)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img___0Rbyn)}
                displayHeight={"378px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"1046px"}
                loading={"lazy"}
                src={{
                  src: rectangle22664Fb5BWkVaqCd,
                  fullWidth: 1046,
                  fullHeight: 378,
                  aspectRatio: 2.767196
                }}
              />

              <Line73Icon
                className={classNames(projectcss.all, sty.svg__iwABc)}
                role={"img"}
              />

              <Line78Icon
                className={classNames(projectcss.all, sty.svg__wRwY3)}
                role={"img"}
              />

              <Line73Icon
                className={classNames(projectcss.all, sty.svg__v5Rf9)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nnw4H
                )}
              >
                {"Stake your LP tokens in our farms to start earning $BSHARE"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__kdcOr
                )}
              >
                {"Bomb Farms"}
              </div>

              <div
                data-plasmic-name={"bombBtcb"}
                data-plasmic-override={overrides.bombBtcb}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.bombBtcb
                )}
              >
                {"BOMB-BTCB "}
              </div>

              <div
                data-plasmic-name={"bombBitcoinLp"}
                data-plasmic-override={overrides.bombBitcoinLp}
                className={classNames(projectcss.all, sty.bombBitcoinLp)}
              />

              <div
                data-plasmic-name={"group3016"}
                data-plasmic-override={overrides.group3016}
                className={classNames(projectcss.all, sty.group3016)}
              >
                <div
                  data-plasmic-name={"bshares5"}
                  data-plasmic-override={overrides.bshares5}
                  className={classNames(projectcss.all, sty.bshares5)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xTdpo
                  )}
                >
                  {"Earned: \n    6.4413 \n≈ $298.88"}
                </div>
              </div>

              <div
                data-plasmic-name={"group3017"}
                data-plasmic-override={overrides.group3017}
                className={classNames(projectcss.all, sty.group3017)}
              >
                <div
                  data-plasmic-name={"bombBitcoinLp2"}
                  data-plasmic-override={overrides.bombBitcoinLp2}
                  className={classNames(projectcss.all, sty.bombBitcoinLp2)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rqmi
                  )}
                >
                  {"Your Stake\n    124.21 \n≈ $1171.62"}
                </div>
              </div>

              <div
                data-plasmic-name={"dailyReturns22"}
                data-plasmic-override={overrides.dailyReturns22}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.dailyReturns22
                )}
              >
                {"Daily Returns: \n2% \r"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hSdmT
                )}
              >
                {"TVL: $1,008,430"}
              </div>

              <p.Stack
                as={"div"}
                data-plasmic-name={"claimRewardsButtons"}
                data-plasmic-override={overrides.claimRewardsButtons}
                hasGap={true}
                className={classNames(projectcss.all, sty.claimRewardsButtons)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iy11G
                  )}
                >
                  {"Claim Rewards"}
                </div>

                {false ? (
                  <div
                    data-plasmic-name={"group535"}
                    data-plasmic-override={overrides.group535}
                    className={classNames(projectcss.all, sty.group535)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__gdXg2)}
                      displayHeight={"18px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"18px"}
                      loading={"lazy"}
                      src={{
                        src: ellipse245ZoZqkrfQbTp,
                        fullWidth: 18,
                        fullHeight: 18,
                        aspectRatio: 1
                      }}
                    />

                    <div
                      data-plasmic-name={"group3037"}
                      data-plasmic-override={overrides.group3037}
                      className={classNames(projectcss.all, sty.group3037)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__r0Jet)}
                        displayHeight={"10px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"10px"}
                        loading={"lazy"}
                        src={{
                          src: union7LuWdpOslfOe,
                          fullWidth: 10,
                          fullHeight: 10,
                          aspectRatio: 1
                        }}
                      />

                      <Union8Icon
                        className={classNames(projectcss.all, sty.svg__wtebc)}
                        role={"img"}
                      />

                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__hDkIq)}
                        displayHeight={"10px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"10px"}
                        loading={"lazy"}
                        src={{
                          src: vector2DiyEuKsIdH,
                          fullWidth: 10,
                          fullHeight: 10,
                          aspectRatio: 1
                        }}
                      />

                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__i8CVk)}
                        displayHeight={"9.998px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"9.978px"}
                        loading={"lazy"}
                        src={{
                          src: maskGroupBli06OE0LN,
                          fullWidth: 9.978,
                          fullHeight: 9.998,
                          aspectRatio: 1
                        }}
                      />

                      <Union9Icon
                        className={classNames(projectcss.all, sty.svg__urBm)}
                        role={"img"}
                      />
                    </div>
                  </div>
                ) : null}
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"claimRewardsButtons2"}
                data-plasmic-override={overrides.claimRewardsButtons2}
                hasGap={true}
                className={classNames(projectcss.all, sty.claimRewardsButtons2)}
              >
                <div
                  data-plasmic-name={"claimRewards"}
                  data-plasmic-override={overrides.claimRewards}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.claimRewards
                  )}
                >
                  {"Claim All"}
                </div>

                {false ? (
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__r1HbB)}
                    displayHeight={"18px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"18px"}
                    loading={"lazy"}
                    src={{
                      src: ellipse245ZoZqkrfQbTp,
                      fullWidth: 18,
                      fullHeight: 18,
                      aspectRatio: 1
                    }}
                  />
                ) : null}
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"withdrawButtons2"}
                data-plasmic-override={overrides.withdrawButtons2}
                hasGap={true}
                className={classNames(projectcss.all, sty.withdrawButtons2)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zZe4M
                  )}
                >
                  {"Withdraw"}
                </div>

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__nI14D)}
                  displayHeight={"21px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"21px"}
                  loading={"lazy"}
                  src={{
                    src: iconArrowDownCircle3FraWzkEdthp,
                    fullWidth: 21,
                    fullHeight: 21,
                    aspectRatio: 1
                  }}
                />
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"depositButtons2"}
                data-plasmic-override={overrides.depositButtons2}
                hasGap={true}
                className={classNames(projectcss.all, sty.depositButtons2)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tyhu8
                  )}
                >
                  {"Deposit"}
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__v2EBb)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__jfcNk)}
                    displayHeight={"21px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"21px"}
                    loading={"lazy"}
                    src={{
                      src: iconArrowDownCircle466Z0Y4Xmkyl,
                      fullWidth: 21,
                      fullHeight: 21,
                      aspectRatio: 1
                    }}
                  />
                </div>
              </p.Stack>

              <div
                data-plasmic-name={"group3018"}
                data-plasmic-override={overrides.group3018}
                className={classNames(projectcss.all, sty.group3018)}
              >
                <div
                  data-plasmic-name={"bshares6"}
                  data-plasmic-override={overrides.bshares6}
                  className={classNames(projectcss.all, sty.bshares6)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hEktu
                  )}
                >
                  {"Earned: \n    6.4413 \n≈ $298.88"}
                </div>
              </div>

              <div
                data-plasmic-name={"group3019"}
                data-plasmic-override={overrides.group3019}
                className={classNames(projectcss.all, sty.group3019)}
              >
                <div
                  data-plasmic-name={"bshareBnbLp"}
                  data-plasmic-override={overrides.bshareBnbLp}
                  className={classNames(projectcss.all, sty.bshareBnbLp)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rhOcj
                  )}
                >
                  {"Your Stake\n    124.21 \n≈ $1171.62"}
                </div>
              </div>

              <div
                data-plasmic-name={"dailyReturns23"}
                data-plasmic-override={overrides.dailyReturns23}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.dailyReturns23
                )}
              >
                {"Daily Returns: \n2% \r"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__godCk
                )}
              >
                {"TVL: $1,008,430"}
              </div>

              <p.Stack
                as={"div"}
                data-plasmic-name={"claimRewardsButtons3"}
                data-plasmic-override={overrides.claimRewardsButtons3}
                hasGap={true}
                className={classNames(projectcss.all, sty.claimRewardsButtons3)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tSXy
                  )}
                >
                  {"Claim Rewards"}
                </div>

                {false ? (
                  <div
                    data-plasmic-name={"group536"}
                    data-plasmic-override={overrides.group536}
                    className={classNames(projectcss.all, sty.group536)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___1R718)}
                      displayHeight={"18px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"18px"}
                      loading={"lazy"}
                      src={{
                        src: ellipse245ZoZqkrfQbTp,
                        fullWidth: 18,
                        fullHeight: 18,
                        aspectRatio: 1
                      }}
                    />

                    <div
                      data-plasmic-name={"group3038"}
                      data-plasmic-override={overrides.group3038}
                      className={classNames(projectcss.all, sty.group3038)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__yncc5)}
                        displayHeight={"10px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"10px"}
                        loading={"lazy"}
                        src={{
                          src: union10ODg7GnkHjdU,
                          fullWidth: 10,
                          fullHeight: 10,
                          aspectRatio: 1
                        }}
                      />

                      <Union11Icon
                        className={classNames(projectcss.all, sty.svg__yfw1I)}
                        role={"img"}
                      />

                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__hoIkB)}
                        displayHeight={"10px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"10px"}
                        loading={"lazy"}
                        src={{
                          src: vector3Cf2Ccicofx,
                          fullWidth: 10,
                          fullHeight: 10,
                          aspectRatio: 1
                        }}
                      />

                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__xpd9D)}
                        displayHeight={"9.998px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"9.978px"}
                        loading={"lazy"}
                        src={{
                          src: maskGroup2IjHoEksC8Si,
                          fullWidth: 9.978,
                          fullHeight: 9.998,
                          aspectRatio: 1
                        }}
                      />

                      <Union12Icon
                        className={classNames(projectcss.all, sty.svg___3MmbK)}
                        role={"img"}
                      />
                    </div>
                  </div>
                ) : null}
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"withdrawButtons3"}
                data-plasmic-override={overrides.withdrawButtons3}
                hasGap={true}
                className={classNames(projectcss.all, sty.withdrawButtons3)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__f50GL
                  )}
                >
                  {"Withdraw"}
                </div>

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__crvoJ)}
                  displayHeight={"21px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"21px"}
                  loading={"lazy"}
                  src={{
                    src: iconArrowDownCircle5MtoDdHGcS6,
                    fullWidth: 21,
                    fullHeight: 21,
                    aspectRatio: 1
                  }}
                />
              </p.Stack>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__sCa7N
                )}
              >
                {"BSHARE-BNB"}
              </div>

              <div
                data-plasmic-name={"bshareBnbLp2"}
                data-plasmic-override={overrides.bshareBnbLp2}
                className={classNames(projectcss.all, sty.bshareBnbLp2)}
              />

              <Rectangle22704Icon
                className={classNames(projectcss.all, sty.svg__w5Vh5)}
                role={"img"}
              />

              <div
                data-plasmic-name={"rectangle22705"}
                data-plasmic-override={overrides.rectangle22705}
                className={classNames(projectcss.all, sty.rectangle22705)}
              />

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame671"}
                data-plasmic-override={overrides.frame671}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame671)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eqqz0
                  )}
                >
                  {"Recommended"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame672"}
                data-plasmic-override={overrides.frame672}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame672)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fnCaP
                  )}
                >
                  {"Recommended"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"depositButtons3"}
                data-plasmic-override={overrides.depositButtons3}
                hasGap={true}
                className={classNames(projectcss.all, sty.depositButtons3)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__buSkg
                  )}
                >
                  {"Deposit"}
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__etkvP)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__keqio)}
                    displayHeight={"21px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"21px"}
                    loading={"lazy"}
                    src={{
                      src: iconArrowDownCircle62T01FdZwcin,
                      fullWidth: 21,
                      fullHeight: 21,
                      aspectRatio: 1
                    }}
                  />
                </div>
              </p.Stack>

              <div
                data-plasmic-name={"group3440"}
                data-plasmic-override={overrides.group3440}
                className={classNames(projectcss.all, sty.group3440)}
              >
                <Ellipse288Icon
                  className={classNames(projectcss.all, sty.svg__tm8Pi)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"bshares7"}
                  data-plasmic-override={overrides.bshares7}
                  className={classNames(projectcss.all, sty.bshares7)}
                />
              </div>

              <div
                data-plasmic-name={"group3442"}
                data-plasmic-override={overrides.group3442}
                className={classNames(projectcss.all, sty.group3442)}
              >
                <Ellipse288Icon
                  className={classNames(projectcss.all, sty.svg__hCw5A)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"bshares8"}
                  data-plasmic-override={overrides.bshares8}
                  className={classNames(projectcss.all, sty.bshares8)}
                />
              </div>

              <div
                data-plasmic-name={"group3443"}
                data-plasmic-override={overrides.group3443}
                className={classNames(projectcss.all, sty.group3443)}
              >
                <Ellipse288Icon
                  className={classNames(projectcss.all, sty.svg__z5VQj)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"bshares9"}
                  data-plasmic-override={overrides.bshares9}
                  className={classNames(projectcss.all, sty.bshares9)}
                />
              </div>
            </div>

            <div
              data-plasmic-name={"rectangle537"}
              data-plasmic-override={overrides.rectangle537}
              className={classNames(projectcss.all, sty.rectangle537)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__iCz03
              )}
            >
              {
                "BBOND can be purchased only on contraction periods, when TWAP of BOMB is below 1"
              }
            </div>

            <Line80Icon
              className={classNames(projectcss.all, sty.svg__kjmAw)}
              role={"img"}
            />

            <div
              data-plasmic-name={"bonds"}
              data-plasmic-override={overrides.bonds}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.bonds
              )}
            >
              {"Bonds "}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__usAnz
              )}
            >
              {"Bomb is over peg"}
            </div>

            {false ? (
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hgtPj
                )}
              >
                {"0.0000 UBond available in wallet"}
              </div>
            ) : null}

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__z5LR
              )}
            >
              {"BBond = 6.2872 BTCB"}
            </div>

            <div
              data-plasmic-name={"currentPriceUnite2"}
              data-plasmic-override={overrides.currentPriceUnite2}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.currentPriceUnite2
              )}
            >
              {"Current Price: (Bomb)^2"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__keHg2
              )}
            >
              {"Purchase BBond"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__zdNf
              )}
            >
              {"Redeem Bomb"}
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"purchaseButtons"}
              data-plasmic-override={overrides.purchaseButtons}
              hasGap={true}
              className={classNames(projectcss.all, sty.purchaseButtons)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dR72F
                )}
              >
                {"Purchase"}
              </div>

              <div
                data-plasmic-name={"group2945"}
                data-plasmic-override={overrides.group2945}
                className={classNames(projectcss.all, sty.group2945)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__yr4T0)}
                  displayHeight={"20px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"20px"}
                  loading={"lazy"}
                  src={{
                    src: vector4E3E4PbP5Bqn,
                    fullWidth: 20,
                    fullHeight: 20,
                    aspectRatio: 1
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__jWsD)}
                  displayHeight={"10.979px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"10.979px"}
                  loading={"lazy"}
                  src={{
                    src: iconShoppingCart6IZqEOiUq,
                    fullWidth: 10.979,
                    fullHeight: 10.979,
                    aspectRatio: 1
                  }}
                />
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"redeemButtons"}
              data-plasmic-override={overrides.redeemButtons}
              hasGap={true}
              className={classNames(projectcss.all, sty.redeemButtons)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jWsf
                )}
              >
                {"Redeem"}
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__a4PoS)}
                displayHeight={"21px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"21px"}
                loading={"lazy"}
                src={{
                  src: iconArrowDownCircle7SBlIKsq5M4,
                  fullWidth: 21,
                  fullHeight: 21,
                  aspectRatio: 1
                }}
              />
            </p.Stack>

            <div
              data-plasmic-name={"group3057"}
              data-plasmic-override={overrides.group3057}
              className={classNames(projectcss.all, sty.group3057)}
            >
              <div
                data-plasmic-name={"availableToRedeem"}
                data-plasmic-override={overrides.availableToRedeem}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.availableToRedeem
                )}
              >
                {"Available to redeem: "}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rs75D
                )}
              >
                {"456"}
              </div>
            </div>

            <div
              data-plasmic-name={"bbond2"}
              data-plasmic-override={overrides.bbond2}
              className={classNames(projectcss.all, sty.bbond2)}
            />

            <div
              data-plasmic-name={"bbond3"}
              data-plasmic-override={overrides.bbond3}
              className={classNames(projectcss.all, sty.bbond3)}
            />

            <div
              data-plasmic-name={"frame677"}
              data-plasmic-override={overrides.frame677}
              className={classNames(projectcss.all, sty.frame677)}
            >
              <div
                data-plasmic-name={"rectangle22708"}
                data-plasmic-override={overrides.rectangle22708}
                className={classNames(projectcss.all, sty.rectangle22708)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gphNk
                )}
              >
                {"Latest News"}
              </div>
            </div>

            <div
              data-plasmic-name={"unity13"}
              data-plasmic-override={overrides.unity13}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.unity13
              )}
            >
              {"Price"}
            </div>

            <div
              data-plasmic-name={"unity14"}
              data-plasmic-override={overrides.unity14}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.unity14
              )}
            >
              {"Current Supply"}
            </div>

            <div
              data-plasmic-name={"unity15"}
              data-plasmic-override={overrides.unity15}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.unity15
              )}
            >
              {"Total Supply"}
            </div>

            <div
              data-plasmic-name={"group3111"}
              data-plasmic-override={overrides.group3111}
              className={classNames(projectcss.all, sty.group3111)}
            >
              <div
                data-plasmic-name={"group3071"}
                data-plasmic-override={overrides.group3071}
                className={classNames(projectcss.all, sty.group3071)}
              >
                <div
                  data-plasmic-name={"rectangle404"}
                  data-plasmic-override={overrides.rectangle404}
                  className={classNames(projectcss.all, sty.rectangle404)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jdlmK
                  )}
                >
                  {"Chat on Discord"}
                </div>
              </div>

              <Ellipse303Icon
                className={classNames(projectcss.all, sty.svg__tQ0Yr)}
                role={"img"}
              />

              <div
                data-plasmic-name={"pw49459141"}
                data-plasmic-override={overrides.pw49459141}
                className={classNames(projectcss.all, sty.pw49459141)}
              />
            </div>

            <div
              data-plasmic-name={"group3112"}
              data-plasmic-override={overrides.group3112}
              className={classNames(projectcss.all, sty.group3112)}
            >
              <div
                data-plasmic-name={"group3072"}
                data-plasmic-override={overrides.group3072}
                className={classNames(projectcss.all, sty.group3072)}
              >
                <div
                  data-plasmic-name={"group2905"}
                  data-plasmic-override={overrides.group2905}
                  className={classNames(projectcss.all, sty.group2905)}
                >
                  <div
                    data-plasmic-name={"rectangle405"}
                    data-plasmic-override={overrides.rectangle405}
                    className={classNames(projectcss.all, sty.rectangle405)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__shGuY
                    )}
                  >
                    {"Read Docs"}
                  </div>
                </div>
              </div>

              <Ellipse303Icon
                className={classNames(projectcss.all, sty.svg___2YrrR)}
                role={"img"}
              />

              <div
                data-plasmic-name={"ww29911061"}
                data-plasmic-override={overrides.ww29911061}
                className={classNames(projectcss.all, sty.ww29911061)}
              />
            </div>

            <div
              data-plasmic-name={"group3069"}
              data-plasmic-override={overrides.group3069}
              className={classNames(projectcss.all, sty.group3069)}
            >
              <div
                data-plasmic-name={"rectangle22701"}
                data-plasmic-override={overrides.rectangle22701}
                className={classNames(projectcss.all, sty.rectangle22701)}
              />

              <div
                data-plasmic-name={"rectangle22702"}
                data-plasmic-override={overrides.rectangle22702}
                className={classNames(projectcss.all, sty.rectangle22702)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xK7I6
                )}
              >
                {"Invest Now"}
              </div>
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__c7E1N
              )}
            >
              {"TVL: $1,008,430"}
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"claimRewardsButtons4"}
              data-plasmic-override={overrides.claimRewardsButtons4}
              hasGap={true}
              className={classNames(projectcss.all, sty.claimRewardsButtons4)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vfGis
                )}
              >
                {"Claim Rewards"}
              </div>

              {false ? (
                <div
                  data-plasmic-name={"group537"}
                  data-plasmic-override={overrides.group537}
                  className={classNames(projectcss.all, sty.group537)}
                >
                  {false ? (
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__cvdet)}
                      displayHeight={"18px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"18px"}
                      loading={"lazy"}
                      src={{
                        src: ellipse245ZoZqkrfQbTp,
                        fullWidth: 18,
                        fullHeight: 18,
                        aspectRatio: 1
                      }}
                    />
                  ) : null}

                  <div
                    data-plasmic-name={"group3039"}
                    data-plasmic-override={overrides.group3039}
                    className={classNames(projectcss.all, sty.group3039)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__jz3Ay)}
                      displayHeight={"10px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"10px"}
                      loading={"lazy"}
                      src={{
                        src: union13ISTlF5VkA,
                        fullWidth: 10,
                        fullHeight: 10,
                        aspectRatio: 1
                      }}
                    />

                    <Union14Icon
                      className={classNames(projectcss.all, sty.svg__gySm9)}
                      role={"img"}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__j0SmD)}
                      displayHeight={"10px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"10px"}
                      loading={"lazy"}
                      src={{
                        src: vector5SDj54U1OSi,
                        fullWidth: 10,
                        fullHeight: 10,
                        aspectRatio: 1
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__p9Zby)}
                      displayHeight={"9.998px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"9.978px"}
                      loading={"lazy"}
                      src={{
                        src: maskGroup3Mw7VoSjZaGe,
                        fullWidth: 9.978,
                        fullHeight: 9.998,
                        aspectRatio: 1
                      }}
                    />

                    <Union15Icon
                      className={classNames(projectcss.all, sty.svg__a962)}
                      role={"img"}
                    />
                  </div>
                </div>
              ) : null}
            </p.Stack>

            <div
              data-plasmic-name={"rectangle539"}
              data-plasmic-override={overrides.rectangle539}
              className={classNames(projectcss.all, sty.rectangle539)}
            />

            <div
              data-plasmic-name={"bomb2"}
              data-plasmic-override={overrides.bomb2}
              className={classNames(projectcss.all, sty.bomb2)}
            />

            <div
              data-plasmic-name={"group3444"}
              data-plasmic-override={overrides.group3444}
              className={classNames(projectcss.all, sty.group3444)}
            >
              <Ellipse288Icon
                className={classNames(projectcss.all, sty.svg___4Egao)}
                role={"img"}
              />

              <div
                data-plasmic-name={"bshares10"}
                data-plasmic-override={overrides.bshares10}
                className={classNames(projectcss.all, sty.bshares10)}
              />
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "dashboard",
    "group241",
    "maskGroup",
    "group375",
    "maskGroup2",
    "bshares",
    "group3029",
    "bshares2",
    "group3030",
    "bomb",
    "withdrawButtons",
    "depositButtons",
    "dailyReturns2",
    "group3053",
    "group3082",
    "rectangle22674",
    "group3042",
    "bbond",
    "unity",
    "group3441",
    "bshares3",
    "unity2",
    "group3084",
    "unity3",
    "unity4",
    "unity5",
    "wMetaMask",
    "unity6",
    "group3085",
    "unity7",
    "unity8",
    "unity9",
    "wMetaMask2",
    "unitePriceTwap",
    "group3083",
    "wMetaMask3",
    "unity10",
    "unity11",
    "unity12",
    "rectangle22703",
    "frame540",
    "group3068",
    "bshares4",
    "group2924",
    "group2904",
    "frame679",
    "group3074",
    "bombBtcb",
    "bombBitcoinLp",
    "group3016",
    "bshares5",
    "group3017",
    "bombBitcoinLp2",
    "dailyReturns22",
    "claimRewardsButtons",
    "group535",
    "group3037",
    "claimRewardsButtons2",
    "claimRewards",
    "withdrawButtons2",
    "depositButtons2",
    "group3018",
    "bshares6",
    "group3019",
    "bshareBnbLp",
    "dailyReturns23",
    "claimRewardsButtons3",
    "group536",
    "group3038",
    "withdrawButtons3",
    "bshareBnbLp2",
    "rectangle22705",
    "frame671",
    "frame672",
    "depositButtons3",
    "group3440",
    "bshares7",
    "group3442",
    "bshares8",
    "group3443",
    "bshares9",
    "rectangle537",
    "bonds",
    "currentPriceUnite2",
    "purchaseButtons",
    "group2945",
    "redeemButtons",
    "group3057",
    "availableToRedeem",
    "bbond2",
    "bbond3",
    "frame677",
    "rectangle22708",
    "unity13",
    "unity14",
    "unity15",
    "group3111",
    "group3071",
    "rectangle404",
    "pw49459141",
    "group3112",
    "group3072",
    "group2905",
    "rectangle405",
    "ww29911061",
    "group3069",
    "rectangle22701",
    "rectangle22702",
    "claimRewardsButtons4",
    "group537",
    "group3039",
    "rectangle539",
    "bomb2",
    "group3444",
    "bshares10"
  ],

  dashboard: [
    "dashboard",
    "group241",
    "maskGroup",
    "group375",
    "maskGroup2",
    "bshares",
    "group3029",
    "bshares2",
    "group3030",
    "bomb",
    "withdrawButtons",
    "depositButtons",
    "dailyReturns2",
    "group3053",
    "group3082",
    "rectangle22674",
    "group3042",
    "bbond",
    "unity",
    "group3441",
    "bshares3",
    "unity2",
    "group3084",
    "unity3",
    "unity4",
    "unity5",
    "wMetaMask",
    "unity6",
    "group3085",
    "unity7",
    "unity8",
    "unity9",
    "wMetaMask2",
    "unitePriceTwap",
    "group3083",
    "wMetaMask3",
    "unity10",
    "unity11",
    "unity12",
    "rectangle22703",
    "frame540",
    "group3068",
    "bshares4",
    "group2924",
    "group2904",
    "frame679",
    "group3074",
    "bombBtcb",
    "bombBitcoinLp",
    "group3016",
    "bshares5",
    "group3017",
    "bombBitcoinLp2",
    "dailyReturns22",
    "claimRewardsButtons",
    "group535",
    "group3037",
    "claimRewardsButtons2",
    "claimRewards",
    "withdrawButtons2",
    "depositButtons2",
    "group3018",
    "bshares6",
    "group3019",
    "bshareBnbLp",
    "dailyReturns23",
    "claimRewardsButtons3",
    "group536",
    "group3038",
    "withdrawButtons3",
    "bshareBnbLp2",
    "rectangle22705",
    "frame671",
    "frame672",
    "depositButtons3",
    "group3440",
    "bshares7",
    "group3442",
    "bshares8",
    "group3443",
    "bshares9",
    "rectangle537",
    "bonds",
    "currentPriceUnite2",
    "purchaseButtons",
    "group2945",
    "redeemButtons",
    "group3057",
    "availableToRedeem",
    "bbond2",
    "bbond3",
    "frame677",
    "rectangle22708",
    "unity13",
    "unity14",
    "unity15",
    "group3111",
    "group3071",
    "rectangle404",
    "pw49459141",
    "group3112",
    "group3072",
    "group2905",
    "rectangle405",
    "ww29911061",
    "group3069",
    "rectangle22701",
    "rectangle22702",
    "claimRewardsButtons4",
    "group537",
    "group3039",
    "rectangle539",
    "bomb2",
    "group3444",
    "bshares10"
  ],

  group241: ["group241", "maskGroup"],
  maskGroup: ["maskGroup"],
  group375: ["group375", "maskGroup2"],
  maskGroup2: ["maskGroup2"],
  bshares: ["bshares"],
  group3029: ["group3029", "bshares2"],
  bshares2: ["bshares2"],
  group3030: ["group3030", "bomb"],
  bomb: ["bomb"],
  withdrawButtons: ["withdrawButtons"],
  depositButtons: ["depositButtons"],
  dailyReturns2: ["dailyReturns2"],
  group3053: ["group3053", "group3082", "rectangle22674", "group3042", "bbond"],
  group3082: ["group3082", "rectangle22674", "group3042", "bbond"],
  rectangle22674: ["rectangle22674"],
  group3042: ["group3042", "bbond"],
  bbond: ["bbond"],
  unity: ["unity"],
  group3441: ["group3441", "bshares3"],
  bshares3: ["bshares3"],
  unity2: ["unity2"],
  group3084: ["group3084", "unity3", "unity4", "unity5", "wMetaMask"],
  unity3: ["unity3"],
  unity4: ["unity4"],
  unity5: ["unity5"],
  wMetaMask: ["wMetaMask"],
  unity6: ["unity6"],
  group3085: ["group3085", "unity7", "unity8", "unity9", "wMetaMask2"],
  unity7: ["unity7"],
  unity8: ["unity8"],
  unity9: ["unity9"],
  wMetaMask2: ["wMetaMask2"],
  unitePriceTwap: ["unitePriceTwap"],
  group3083: ["group3083", "wMetaMask3", "unity10", "unity11", "unity12"],
  wMetaMask3: ["wMetaMask3"],
  unity10: ["unity10"],
  unity11: ["unity11"],
  unity12: ["unity12"],
  rectangle22703: ["rectangle22703"],
  frame540: ["frame540"],
  group3068: ["group3068", "bshares4"],
  bshares4: ["bshares4"],
  group2924: ["group2924", "group2904", "frame679"],
  group2904: ["group2904", "frame679"],
  frame679: ["frame679"],
  group3074: [
    "group3074",
    "bombBtcb",
    "bombBitcoinLp",
    "group3016",
    "bshares5",
    "group3017",
    "bombBitcoinLp2",
    "dailyReturns22",
    "claimRewardsButtons",
    "group535",
    "group3037",
    "claimRewardsButtons2",
    "claimRewards",
    "withdrawButtons2",
    "depositButtons2",
    "group3018",
    "bshares6",
    "group3019",
    "bshareBnbLp",
    "dailyReturns23",
    "claimRewardsButtons3",
    "group536",
    "group3038",
    "withdrawButtons3",
    "bshareBnbLp2",
    "rectangle22705",
    "frame671",
    "frame672",
    "depositButtons3",
    "group3440",
    "bshares7",
    "group3442",
    "bshares8",
    "group3443",
    "bshares9"
  ],

  bombBtcb: ["bombBtcb"],
  bombBitcoinLp: ["bombBitcoinLp"],
  group3016: ["group3016", "bshares5"],
  bshares5: ["bshares5"],
  group3017: ["group3017", "bombBitcoinLp2"],
  bombBitcoinLp2: ["bombBitcoinLp2"],
  dailyReturns22: ["dailyReturns22"],
  claimRewardsButtons: ["claimRewardsButtons", "group535", "group3037"],
  group535: ["group535", "group3037"],
  group3037: ["group3037"],
  claimRewardsButtons2: ["claimRewardsButtons2", "claimRewards"],
  claimRewards: ["claimRewards"],
  withdrawButtons2: ["withdrawButtons2"],
  depositButtons2: ["depositButtons2"],
  group3018: ["group3018", "bshares6"],
  bshares6: ["bshares6"],
  group3019: ["group3019", "bshareBnbLp"],
  bshareBnbLp: ["bshareBnbLp"],
  dailyReturns23: ["dailyReturns23"],
  claimRewardsButtons3: ["claimRewardsButtons3", "group536", "group3038"],
  group536: ["group536", "group3038"],
  group3038: ["group3038"],
  withdrawButtons3: ["withdrawButtons3"],
  bshareBnbLp2: ["bshareBnbLp2"],
  rectangle22705: ["rectangle22705"],
  frame671: ["frame671"],
  frame672: ["frame672"],
  depositButtons3: ["depositButtons3"],
  group3440: ["group3440", "bshares7"],
  bshares7: ["bshares7"],
  group3442: ["group3442", "bshares8"],
  bshares8: ["bshares8"],
  group3443: ["group3443", "bshares9"],
  bshares9: ["bshares9"],
  rectangle537: ["rectangle537"],
  bonds: ["bonds"],
  currentPriceUnite2: ["currentPriceUnite2"],
  purchaseButtons: ["purchaseButtons", "group2945"],
  group2945: ["group2945"],
  redeemButtons: ["redeemButtons"],
  group3057: ["group3057", "availableToRedeem"],
  availableToRedeem: ["availableToRedeem"],
  bbond2: ["bbond2"],
  bbond3: ["bbond3"],
  frame677: ["frame677", "rectangle22708"],
  rectangle22708: ["rectangle22708"],
  unity13: ["unity13"],
  unity14: ["unity14"],
  unity15: ["unity15"],
  group3111: ["group3111", "group3071", "rectangle404", "pw49459141"],
  group3071: ["group3071", "rectangle404"],
  rectangle404: ["rectangle404"],
  pw49459141: ["pw49459141"],
  group3112: [
    "group3112",
    "group3072",
    "group2905",
    "rectangle405",
    "ww29911061"
  ],

  group3072: ["group3072", "group2905", "rectangle405"],
  group2905: ["group2905", "rectangle405"],
  rectangle405: ["rectangle405"],
  ww29911061: ["ww29911061"],
  group3069: ["group3069", "rectangle22701", "rectangle22702"],
  rectangle22701: ["rectangle22701"],
  rectangle22702: ["rectangle22702"],
  claimRewardsButtons4: ["claimRewardsButtons4", "group537", "group3039"],
  group537: ["group537", "group3039"],
  group3039: ["group3039"],
  rectangle539: ["rectangle539"],
  bomb2: ["bomb2"],
  group3444: ["group3444", "bshares10"],
  bshares10: ["bshares10"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    dashboard: makeNodeComponent("dashboard"),
    group241: makeNodeComponent("group241"),
    maskGroup: makeNodeComponent("maskGroup"),
    group375: makeNodeComponent("group375"),
    maskGroup2: makeNodeComponent("maskGroup2"),
    bshares: makeNodeComponent("bshares"),
    group3029: makeNodeComponent("group3029"),
    bshares2: makeNodeComponent("bshares2"),
    group3030: makeNodeComponent("group3030"),
    bomb: makeNodeComponent("bomb"),
    withdrawButtons: makeNodeComponent("withdrawButtons"),
    depositButtons: makeNodeComponent("depositButtons"),
    dailyReturns2: makeNodeComponent("dailyReturns2"),
    group3053: makeNodeComponent("group3053"),
    group3082: makeNodeComponent("group3082"),
    rectangle22674: makeNodeComponent("rectangle22674"),
    group3042: makeNodeComponent("group3042"),
    bbond: makeNodeComponent("bbond"),
    unity: makeNodeComponent("unity"),
    group3441: makeNodeComponent("group3441"),
    bshares3: makeNodeComponent("bshares3"),
    unity2: makeNodeComponent("unity2"),
    group3084: makeNodeComponent("group3084"),
    unity3: makeNodeComponent("unity3"),
    unity4: makeNodeComponent("unity4"),
    unity5: makeNodeComponent("unity5"),
    wMetaMask: makeNodeComponent("wMetaMask"),
    unity6: makeNodeComponent("unity6"),
    group3085: makeNodeComponent("group3085"),
    unity7: makeNodeComponent("unity7"),
    unity8: makeNodeComponent("unity8"),
    unity9: makeNodeComponent("unity9"),
    wMetaMask2: makeNodeComponent("wMetaMask2"),
    unitePriceTwap: makeNodeComponent("unitePriceTwap"),
    group3083: makeNodeComponent("group3083"),
    wMetaMask3: makeNodeComponent("wMetaMask3"),
    unity10: makeNodeComponent("unity10"),
    unity11: makeNodeComponent("unity11"),
    unity12: makeNodeComponent("unity12"),
    rectangle22703: makeNodeComponent("rectangle22703"),
    frame540: makeNodeComponent("frame540"),
    group3068: makeNodeComponent("group3068"),
    bshares4: makeNodeComponent("bshares4"),
    group2924: makeNodeComponent("group2924"),
    group2904: makeNodeComponent("group2904"),
    frame679: makeNodeComponent("frame679"),
    group3074: makeNodeComponent("group3074"),
    bombBtcb: makeNodeComponent("bombBtcb"),
    bombBitcoinLp: makeNodeComponent("bombBitcoinLp"),
    group3016: makeNodeComponent("group3016"),
    bshares5: makeNodeComponent("bshares5"),
    group3017: makeNodeComponent("group3017"),
    bombBitcoinLp2: makeNodeComponent("bombBitcoinLp2"),
    dailyReturns22: makeNodeComponent("dailyReturns22"),
    claimRewardsButtons: makeNodeComponent("claimRewardsButtons"),
    group535: makeNodeComponent("group535"),
    group3037: makeNodeComponent("group3037"),
    claimRewardsButtons2: makeNodeComponent("claimRewardsButtons2"),
    claimRewards: makeNodeComponent("claimRewards"),
    withdrawButtons2: makeNodeComponent("withdrawButtons2"),
    depositButtons2: makeNodeComponent("depositButtons2"),
    group3018: makeNodeComponent("group3018"),
    bshares6: makeNodeComponent("bshares6"),
    group3019: makeNodeComponent("group3019"),
    bshareBnbLp: makeNodeComponent("bshareBnbLp"),
    dailyReturns23: makeNodeComponent("dailyReturns23"),
    claimRewardsButtons3: makeNodeComponent("claimRewardsButtons3"),
    group536: makeNodeComponent("group536"),
    group3038: makeNodeComponent("group3038"),
    withdrawButtons3: makeNodeComponent("withdrawButtons3"),
    bshareBnbLp2: makeNodeComponent("bshareBnbLp2"),
    rectangle22705: makeNodeComponent("rectangle22705"),
    frame671: makeNodeComponent("frame671"),
    frame672: makeNodeComponent("frame672"),
    depositButtons3: makeNodeComponent("depositButtons3"),
    group3440: makeNodeComponent("group3440"),
    bshares7: makeNodeComponent("bshares7"),
    group3442: makeNodeComponent("group3442"),
    bshares8: makeNodeComponent("bshares8"),
    group3443: makeNodeComponent("group3443"),
    bshares9: makeNodeComponent("bshares9"),
    rectangle537: makeNodeComponent("rectangle537"),
    bonds: makeNodeComponent("bonds"),
    currentPriceUnite2: makeNodeComponent("currentPriceUnite2"),
    purchaseButtons: makeNodeComponent("purchaseButtons"),
    group2945: makeNodeComponent("group2945"),
    redeemButtons: makeNodeComponent("redeemButtons"),
    group3057: makeNodeComponent("group3057"),
    availableToRedeem: makeNodeComponent("availableToRedeem"),
    bbond2: makeNodeComponent("bbond2"),
    bbond3: makeNodeComponent("bbond3"),
    frame677: makeNodeComponent("frame677"),
    rectangle22708: makeNodeComponent("rectangle22708"),
    unity13: makeNodeComponent("unity13"),
    unity14: makeNodeComponent("unity14"),
    unity15: makeNodeComponent("unity15"),
    group3111: makeNodeComponent("group3111"),
    group3071: makeNodeComponent("group3071"),
    rectangle404: makeNodeComponent("rectangle404"),
    pw49459141: makeNodeComponent("pw49459141"),
    group3112: makeNodeComponent("group3112"),
    group3072: makeNodeComponent("group3072"),
    group2905: makeNodeComponent("group2905"),
    rectangle405: makeNodeComponent("rectangle405"),
    ww29911061: makeNodeComponent("ww29911061"),
    group3069: makeNodeComponent("group3069"),
    rectangle22701: makeNodeComponent("rectangle22701"),
    rectangle22702: makeNodeComponent("rectangle22702"),
    claimRewardsButtons4: makeNodeComponent("claimRewardsButtons4"),
    group537: makeNodeComponent("group537"),
    group3039: makeNodeComponent("group3039"),
    rectangle539: makeNodeComponent("rectangle539"),
    bomb2: makeNodeComponent("bomb2"),
    group3444: makeNodeComponent("group3444"),
    bshares10: makeNodeComponent("bshares10"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
